// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbzmkesvjvncrgmvdcqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiem1rZXN2anZuY3JnbXZkY3FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjM3ODEsImV4cCI6MjA3NDQ5OTc4MX0.XiqBaOiOJHObZAf4raB-gkLGs5sqQjCnv0bXFOhEFuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});